### ISSUE TITLE
Getting error when running dredd

### ISSUE THREAD

**Issue by warrence** [ddelnano/dredd-hooks-php#16]
Hi, I often get the error below when running dredd.

```
dredd --language vendor/bin/dredd-hooks-php --hookfiles=./dredd-hooks-php/hooks*.php
info: Configuration dredd.yml found, ignoring other arguments.
info: Using apiary reporter.
info: Beginning Dredd testing...
info: Found Hookfiles: ./dredd-hooks-php/hooks_test.php
info: Spawning `vendor/bin/dredd-hooks-php` hooks handler
warn: Error connecting to the hook handler. Is the handler running? Retrying...
warn: Error connecting to the hook handler. Is the handler running? Retrying...
info: Hook handler stdout: Starting server

warn: Error connecting to the hook handler. Is the handler running? Retrying...
info: Connected to the hook handler, waiting 0.5s to start testing.
fail: PUT /permissions/1 duration: 383ms
warn: Hook handling timed out.
pass: POST /permissions duration: NaNms
pass: GET /permissions/1 duration: NaNms
pass: POST /permissions/search duration: NaNms
pass: DELETE /permissions/1 duration: NaNms
pass: PUT /roles/1 duration: NaNms
pass: POST /roles duration: NaNms
pass: GET /roles/1 duration: NaNms
warn: Hook handling timed out.
fail: POST /roles/search duration: 5290ms
/Users/warrence1/npm/lib/node_modules/dredd/lib/reporters/apiary-reporter.js:287
    postData = JSON.stringify(body);
                    ^
TypeError: Converting circular structure to JSON
  at Object.stringify (native)
  at ApiaryReporter._performRequestAsync (/Users/warrence1/npm/lib/node_modules/dredd/lib/reporters/apiary-reporter.js:287:21)
  at ApiaryReporter._performRequestAsync (/Users/warrence1/npm/lib/node_modules/dredd/lib/reporters/apiary-reporter.js:3:57)
  at EventEmitter.<anonymous> (/Users/warrence1/npm/lib/node_modules/dredd/lib/reporters/apiary-reporter.js:140:22)
  at EventEmitter.emit (events.js:129:20)
  at TransactionRunner.emitResult (/Users/warrence1/npm/lib/node_modules/dredd/lib/transaction-runner.js:424:38)
  at /Users/warrence1/npm/lib/node_modules/dredd/lib/transaction-runner.js:108:34
  at TransactionRunner.runHooksForData (/Users/warrence1/npm/lib/node_modules/dredd/lib/transaction-runner.js:210:14)
  at /Users/warrence1/npm/lib/node_modules/dredd/lib/transaction-runner.js:104:32
  at /Users/warrence1/npm/lib/node_modules/dredd/lib/transaction-runner.js:207:16
  at /Users/warrence1/npm/lib/node_modules/dredd/node_modules/async/lib/async.js:251:17
  at /Users/warrence1/npm/lib/node_modules/dredd/node_modules/async/lib/async.js:154:25
  at /Users/warrence1/npm/lib/node_modules/dredd/node_modules/async/lib/async.js:248:21
  at /Users/warrence1/npm/lib/node_modules/dredd/lib/transaction-runner.js:157:24
  at /Users/warrence1/npm/lib/node_modules/dredd/lib/transaction-runner.js:318:18
  at [object Object].handleTimeout [as _onTimeout] (/Users/warrence1/npm/lib/node_modules/dredd/lib/hooks-worker-client.js:325:20)
  at Timer.listOnTimeout (timers.js:119:15)
```

Sometimes is ok, sometimes is not, please help.

**Comment by ddelnano** [comment]
I do not have much experience with the dredd internals @netmilk

**Comment by ddelnano** [comment]
Actually I am gonna close this.  I would put the issue on the dredd repo instead since this is a dredd specific thing.  I will still get back to you about #15

**Comment by warrence** [comment]
For the error with the dredd internals, i have found the fix, just wanna share here incase anyone else facing the same problem. It is because when some function take longer time to process, somehow the error display is not helpful enough to identify the problem. My fix is to change the hooks-worker-timeout: 10000 to higher value.

**Comment by ddelnano** [comment]
Cool thanks for updating this.
