### ISSUE TITLE
Cannot connect to hooks server with Python.

### ISSUE THREAD

**Issue by justinabrahms** [ddelnano/dredd-hooks-php#7]
Hi there. I can't seem to connect to the hooks server from my python hooks. Config files below. I saw this issue https://github.com/ddelnano/dredd-hooks-php/issues/3 but it doesn't appear to be an issue with start time of the hooks. I edited the installed version of dredd to make the timeout on waiting for the hooks server 10 seconds instead of 1, but still no luck. If I run the hooks command manually, it just sits there (which I would expect it's supposed to do, waiting for input?).
#### Error

```
$ ./node_modules/.bin/dredd
Configuration dredd.yml found, ignoring other arguments.
info: Using apiary reporter.
warn: Apiary reporter environment variable APIARY_API_KEY or APIARY_API_NAME not defined.
info: Beginning Dredd testing...
Spawning `python` hooks handler
Hook handler stderr: ccxcon/apiary_hooks.py:1: RuntimeWarning: Parent module 'apiary_hooks' not found while handling absolute import
  from dredd_hooks import hooks
Traceback (most recent call last):
  File "/home/jabrahms/.virtualenvs/ccxcon/bin/dredd-hooks-python", line 13, in <module>
    dredd.main(sys.argv[1:])
  File "/home/jabrahms/.virtualenvs/ccxcon/local/lib/python2.7/site-packages/dredd_hooks/dredd.py", line 222, in main
    load_hook_files(a)
  File "/home/jabrahms/.virtualenvs/ccxcon/local/lib/python2.7/site-packages/dredd_hooks/dredd.py", line 128, in load_hook_files
    module = imp.load_source(os.path.basename(path), path)
  File "ccxcon/apiary_hooks.py", line 1, in <module>
    from dredd_hooks import hooks
ImportError: cannot import name hooks

Error connecting to the hook handler. Is the handler running?
{ [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
```
#### dredd.yml

```
dry-run: false
hookfiles: 'ccxcon/apiary_hooks.py'
language: python
sandbox: false
init: false
custom: {}
names: false
only: []
reporter: apiary
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
blueprint: apiary.apib
endpoint: 'http://localhost:8000/'
# server: ./manage.py runserver   # I've been running this as a separate process
# server-wait: 3
```
#### ccxcon/apiary_hooks.py

``` python
from dredd_hooks import hooks

@hooks.before("info: Courses > Courses Collection > List All Courses")
def skip_test(transaction):
    transaction['skip'] = True
```

**Comment by justinabrahms** [comment]
Looks as though I had things misconfigured in my hooks. It should have been `import dredd_hooks as hooks` :-/

**Comment by ddelnano** [comment]
Ok so it is working now?

**Comment by justinabrahms** [comment]
Seems to be. Thank you.

**Comment by ddelnano** [comment]
:+1:
